export { default as Collection } from './Collection';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Product } from './Product';
export { default as Home } from './Home';
export { default as Cart } from './Cart';
export { default as Login } from './Login';
export { default as Orders } from './Orders';
export { default as PlaceOrders } from './PlaceOrders';
